[template]
src = "orthanc.json.tmpl"
dest = "/etc/orthanc/orthanc.json"
keys = [
    "/orthanc/name",
    "/orthanc/aetitle",

    "/orthanc/max/size",
    "/orthanc/max/patients",

    "/orthanc/store/dicom",

    "/orthanc/remote/allow",
    "/orthanc/remote/auth",
    "/orthanc/remote/user",
    "/orthanc/remote/password",

    "/orthanc/pg/enabled",
    "/orthanc/pg/host",
    "/orthanc/pg/port",
    "/orthanc/pg/user",
    "/orthanc/pg/password",
    "/orthanc/pg/database"
]