[template]
src = "routing.lua.tmpl"
dest = "/var/lib/orthanc/scripts/routing.lua"
keys = [
    "/orthanc/route/enabled",
    "/orthanc/route/and/store",
    "/orthanc/route/to/peers",
    "/orthanc/route/to/mods",
]